djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('teacher.urls')),
    path('', include('userextend.urls')),
    path('', include('course.urls')),
    path('', include('django.contrib.auth.urls')),
]

home/urls.py
from django.urls import path
from home import views

# constructia unui url
urlpatterns = [
    path('page/', views.homepage, name='page'),
    path('all_students/', views.home, name='list_of_students'),
    path('masini/', views.brands, name='masini'),
    path('', views.HomeTemplateView.as_view(), name='homepage')

]

teacher/urls.py
from django.urls import path

from teacher import views

urlpatterns = [
    path('create_teacher/', views.TeacherCreateView.as_view(), name='create-teacher'),
    path('list_of_teacher/', views.TeacherListView.as_view(), name='list-of-teachers'),
    path('update_teacher/<int:pk>/', views.TeacherUpdateView.as_view(), name='update-teacher'),
    path('delete_teacher/<int:pk>/', views.TeacherDeleteView.as_view(), name='delete-teacher'),
    path('detail_teacher/<int:pk>/', views.TeacherDetailView.as_view(), name='detail-teacher'),
    path('student_per_teacher/<int:id_teacher>/', views.get_all_students_per_teacher, name='student-per-teachers')
]

teacher/models.py
from django.db import models


class Teacher(models.Model):
    gender_choices = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )

    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)
    specialisation = models.CharField(max_length=30, null=True)
    date_of_birth = models.DateField(null=True)
    active = models.BooleanField(default=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.specialisation}'

teacher/forms.py
from django import forms
from django.forms import TextInput

from teacher.models import Teacher


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        # fields = '__all__' # campurile pe care le vrem in formular
        fields = ['first_name', 'last_name', 'date_of_birth', 'specialisation'
                  ]
        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'Please enter your first name', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'Please enter your last name', 'class': 'form-control'}),
            'specialisation': TextInput(attrs={'placeholder': 'Please enter your specialisation', 'class': 'form-control'}),
            'date_of_birth': TextInput(attrs={'class': 'form-control', 'type': 'date'}),

        }

teacher/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from student.models import Student
from teacher.filters import TeacherFilters
from teacher.forms import TeacherForm
from teacher.models import Teacher


# mai jos creem formularul
class TeacherCreateView(LoginRequiredMixin, CreateView):
    template_name = 'teacher/create_teacher.html'  # calea catre fisierul html unde va fi afisat formularul
    model = Teacher                                 # modelul=tabelul pe care il folosim in generarea formuarului
    # fields = '__all__'                            # campurile pe care le vrem in formular
    success_url = reverse_lazy('create-teacher')  # redirectionarea dupa ce formularul a fost salvat
    form_class = TeacherForm


class TeacherListView(LoginRequiredMixin, ListView):
    template_name = 'teacher/list_teacher.html'
    model = Teacher
    context_object_name = 'all_teachers'

    def get_context_data(self, **kwargs):
        data = super(TeacherListView, self).get_context_data(**kwargs)
        all_teachers = Teacher.objects.all()
        my_filter = TeacherFilters(self.request.GET, queryset=all_teachers)
        all_teachers = my_filter.qs
        data['all_teachers'] = all_teachers
        data['my_filter'] = my_filter
        return data


class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'teacher/update_teacher.html'
    model = Teacher
    success_url = reverse_lazy('list-of-teachers')
    form_class = TeacherForm


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'teacher/delete_teacher.html'
    model = Teacher
    success_url = reverse_lazy('list-of-teachers')


class TeacherDetailView(LoginRequiredMixin, DetailView):
    template_name = 'teacher/detail_teacher.html'
    model = Teacher


def get_all_students_per_teacher(request, id_teacher):
    all_students_per_teacher = Student.objects.filter(teacher_id=id_teacher)
    context = {'students': all_students_per_teacher}
    return render(request, 'student/get_all_students_per_teacher.html', context)

templates/teacher/create_teacher.html
{% extends 'base.html' %}
{% block title %} Create a new teacher{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="POST">
            {% csrf_token %} {# securitate #}
            {{ form.as_p }} {# genereaza formularul #}
            <button type="submit" class="btn btn-primary">Save</button>
            {# buton salveaza in baza de date #}
        </form>
    </div>
</div>
{% endblock %}

templates/teacher/delete_teacher.html
{% extends 'base.html' %}
{% block title %} Delete teacher{% endblock %}
{% block content %}
    <p> Are you sure to delete {{ teacher.first_name }} {{ teacher.last_name }}?</p>
    <form method="post"
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Yes</button>
    <a href="{% url 'list-of-teachers' %}" class="btn btn-default">No</a>
    <button type="button" onclick="location.href='{% url 'list-of-teachers' %}'">No, sure</button>
{% endblock %}

templates/teacher/detail_teacher.html
{% extends 'base.html' %}
{% block title %} More information {% endblock %}

{% block content %}
    <div class="card text-center">
        <div class="card-header">
            {{ teacher.created_at }}
            </div>
                <div class="card-body">
                    <h5 class="card-title"> {{ teacher.first_name }} {{ teacher.last_name }}</h5>
                    <p class="card-text">Specialisation: {{ teacher.specialisation }}. </p>
                    <a href="{% url 'list-of-teachers' %}" class="btn btn-primary">Go to list of teacher</a>
                </div>
            <div class="card-footer text-muted">
            Updated at {{ teacher.updated_at }}
        </div>
    </div>
{% endblock %}

templates/teacher/list_teacher.html
{%  extends 'base.html' %}
{%  block title %} List of teachers {% endblock %}

{% block content %}
    <form method="get">
    {{ my_filter.form }}
    <button type="submit" class="btn btn-success">Search</button>
    </form>
    <div class="row">
    {% for teacher in all_teachers %}
            <div class="card" style="width: 20rem; margin-right: 15px">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ teacher.first_name }} {{ teacher.last_name }}</h5>
                    <p class="card-text">Specialisation: {{ teacher.specialisation  }}</p>
                </div>
            <div class="card-footer">
                {%  if perms.teacher.change_teacher %}
                  <a href="{% url 'update-teacher' teacher.id %}" class="btn btn-primary">Update</a>
                {% endif %}
                {%  if perms.teacher.delete_teacher %}
                    <a href="{% url 'delete-teacher' teacher.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
                {% if perms.teacher.view_teacher %}
                    <a href="{% url 'detail-teacher' teacher.id %}" class="btn btn-primary">Details</a>
                {% endif %}
            </div>
            </div>
    {% endfor %}
    </div>
{% endblock %}

templates/teacher/update_teacher.html
{% extends 'base.html' %}
{% block title %} Update teacher {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
{% endblock %}